sonar.projectKey=ISCOUTB_AS_202620_DinamikUTB
sonar.organization=isco-utb

sonar.sources=backend/app,frontend/lib
sonar.tests=backend/tests,frontend/test

sonar.exclusions=frontend/linux/*,frontend/macos/,frontend/windows/,frontend/android/,frontend/ios/,frontend/web/*

sonar.python.version=3.12
